services:
  backend:
    build: backend/.
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=se_db
      - DB_USER=se_admin
      - DB_PASSWORD=se_pass

  database:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=se_db
      - POSTGRES_USER=se_admin
      - POSTGRES_PASSWORD=se_pass

volumes:
  pg_data:
